### ISSUE TITLE
Making Javascript Better

### ISSUE THREAD

**Issue by ijayoa** [katekimani/katekimani.github.io#1]
remove image closing tags
Add p tags containing image titles beneath image tag

get image title by querying for the next element in the dom
var p = $(this).next() 

Get text in the paragraph tag

var ptext = p.text()

then construct html to inject
var imgtitle =  '<p>' + ptext + '</p>'

concatenate with img

old - modal-body....html(img)

replace with  - html(img + imgtitle);

**Comment by katekimani** [comment]
Hi Ij,

I am so grateful for your time. Will make the updates.

Thank you,
Kate Kimani.

**Comment by ijayoa** [comment]
always welcome

:)

**Comment by katekimani** [comment]
Hi Ij,
It is working beautifully now.

Thank you.

**Comment by ijayoa** [comment]
always welcome

kate.
